dotenv: .env
wallets:
  pkey_lb_official: ${PKEY_LB_OFFICIAL}
  pkey_lb_resolver: ${PKEY_LB_RESOLVER}
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.5.0
compiler:
  solc:
    remappings:
      - '@openzeppelin/contracts=OpenZeppelin/openzeppelin-contracts@4.5.0/contracts'